config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :photos, only:[:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
      patch :confirm
    end
  end
  root 'top#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  validates :title, presence: true
  mount_uploader :photo, PhotoUploader
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable
  mount_uploader :avatar, AvatarUploader
  has_many :photos

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(
        name: auth.extra.raw_info.name,
        provider: auth.provider,
        uid: auth.uid,
        email: auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
        image_url: auth.info.image,
        password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
        name: auth.info.nickname,
        image_url: auth.info.image,
        provider: auth.provider,
        uid: auth.uid,
        email: auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
        password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_actionで下で定義したメソッドを実行
  before_action :configure_permitted_parameters, if: :devise_controller?

  #変数PERMISSIBLE_ATTRIBUTESに配列[:name]を代入
  PERMISSIBLE_ATTRIBUTES = %i(name avatar avatar_cache)

  protected

    #deviseのストロングパラメーターにカラム追加するメソッドを定義
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_photo, only:[:edit, :update, :destroy]

  def index
    @photos = Photo.all
  end

  def new
    if params[:back]
      @photo = Photo.new(photos_params)
    else
      @photo = Photo.new
    end
  end

  def create
    @photo = Photo.new(photos_params)
    @photo.user_id = current_user.id
    if @photo.save
      redirect_to photos_path, notice: "作成が完了しました！"
      NoticeMailer.sendmail_photo(@photo).deliver
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @photo.update(photos_params)
    redirect_to photos_path, notice: "編集が完了しました！"
  end

  def destroy
    @photo.destroy
    redirect_to photos_path, notice: "削除が完了しました！"
  end

  def confirm
    @photo = Photo.new(photos_params)
    render :new if @photo.invalid?
  end

private
  def photos_params
    params.require(:photo).permit(:title, :photo, :content)
  end

  def set_photo
    @photo = Photo.find(params[:id])
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook")if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def profile_img(user)
    return image_tag(user.avatar, alt: user.name) if user.avatar?
    
    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'no_image.png'
    end
    image_tag(img_url, alt: user.name)
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
  def choose_new_or_edit
    if action_name =='new' || action_name == 'confirm'
      confirm_photos_path
    elsif action_name == 'edit'
      confirm_photos_path
    end
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Examgram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <header>
    <ul>
      <li><%= link_to "トップページ", root_path %></li>
      <li><%= link_to "Examgram", photos_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'ユーザー設定', edit_user_registration_path %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path %></li>
        <li><%= link_to 'サインアップ', new_user_registration_path %></li>
      <% end %>
    </ul>
  </header>

<%= yield %>

  <footer>
    <p>
       Ruby on Rails練習用<br>
       写真投稿アプリ
    </p>
  </footer>


</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= @photo.errors.count %>件のエラーがあります。</h2>

      <ul>
        <% @photo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
  <br>
  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
    <br>
  </div>

  <%= f.label :content %>
  <%= f.text_field :content, class: 'form-control' %>
  <br>
  <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to "写真一覧に戻る", photos_path %>

app/views/photos/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で送信します。</h3>

    <%= form_for(@photo) do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :photo %>
      <%= f.hidden_field :content %>
      <p>タイトル：<%= @photo.title %></p>
      <p>写真：<%= image_tag @photo.photo.url %></p>
      <p>本文：<%= @photo.content %></p>
      <%= f.submit "投稿する", class: 'btn btn-primary btn-block' %>
    <% end %>

    <%= form_for(@photo, url: new_photo_path, method: 'get') do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :photo %>
      <%= f.hidden_field :content %>
      <%= f.submit "戻る",name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>

  </div>
</div>

app/views/photos/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>編集する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/photos/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
          <%= link_to "写真を投稿する", new_photo_path, class: 'btn btn-default' %>
    <% @photos.each do |photo| %>
      <div class="row">
        <div class="contributor">
          <%= profile_img(photo.user) if profile_img(photo.user)%>
          <%= photo.user.name %>
        </div>
        <p>タイトル：<%= photo.title %></p>
        <%= image_tag photo.photo.url %>
        <p>説明：<%= photo.content %></p>
        <%= link_to "編集", edit_photo_path(photo.id),data: { confirm: '本当に編集しますか？'}, class: 'btn btn-default btn-sm btn-success' %>
        <%= link_to "削除", photo_path(photo.id), method: :delete, data: { confirm: '本当に削除しますか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
      </div>
    <% end %>
  </div>
</div>

app/views/photos/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>写真を投稿する</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/top/index.html.erb
<section class="main-header">
  <p class="flash"><%= notice %><%= alert %></p>
  <img src="<%= asset_path "smartphone.png" %>">
</section>
<section class="about">
  <h1>Examgram</h1>
</section>